### ISSUE TITLE
Segmentation Fault on Mac Mavericks

### ISSUE THREAD

**Issue by ddd1600** [ngs/rb-blink1#20]
2.0.0-p598 :004 > b.set_rgb(255, 0, 0)
(irb):4: [BUG] Segmentation fault
ruby 2.0.0p598 (2014-11-13 revision 48408) [x86_64-darwin13.4.0]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     \* ~/Library/Logs/CrashReporter
     \* /Library/Logs/CrashReporter
     \* ~/Library/Logs/DiagnosticReports
     \* /Library/Logs/DiagnosticReports
   the more detail of.

-- Control frame information -----------------------------------------------
c:0019 p:---- s:0078 e:000077 CFUNC  :set_rgb
c:0018 p:0010 s:0072 e:000071 EVAL   (irb):4 [FINISH]
c:0017 p:---- s:0070 e:000069 CFUNC  :eval
c:0016 p:0024 s:0063 e:000062 METHOD /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/workspace.rb:86
c:0015 p:0025 s:0056 e:000054 METHOD /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/context.rb:380
c:0014 p:0022 s:0050 e:000049 BLOCK  /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb.rb:492
c:0013 p:0040 s:0042 e:000041 METHOD /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb.rb:624
c:0012 p:0009 s:0037 e:000036 BLOCK  /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb.rb:489
c:0011 p:0118 s:0033 e:000032 BLOCK  /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/ruby-lex.rb:247 [FINISH]
c:0010 p:---- s:0030 e:000029 CFUNC  :loop
c:0009 p:0007 s:0027 e:000026 BLOCK  /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/ruby-lex.rb:233 [FINISH]
c:0008 p:---- s:0025 e:000024 CFUNC  :catch
c:0007 p:0015 s:0021 e:000020 METHOD /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/ruby-lex.rb:232
c:0006 p:0030 s:0018 E:001b88 METHOD /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb.rb:488
c:0005 p:0008 s:0015 e:000014 BLOCK  /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb.rb:397 [FINISH]
c:0004 p:---- s:0013 e:000012 CFUNC  :catch
c:0003 p:0143 s:0009 E:001e68 METHOD /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb.rb:396
c:0002 p:0031 s:0004 E:001fd8 EVAL   /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/bin/irb:12 [FINISH]
c:0001 p:0000 s:0002 E:0007a8 TOP    [FINISH]

/Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/bin/irb:12:in `<main>'
/Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb.rb:396:in`start'
/Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb.rb:396:in `catch'
/Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb.rb:397:in`block in start'
/Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb.rb:488:in `eval_input'
/Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/ruby-lex.rb:232:in`each_top_level_statement'
/Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/ruby-lex.rb:232:in `catch'
/Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/ruby-lex.rb:233:in`block in each_top_level_statement'
/Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/ruby-lex.rb:233:in `loop'
/Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/ruby-lex.rb:247:in`block (2 levels) in each_top_level_statement'
/Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb.rb:489:in `block in eval_input'
/Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb.rb:624:in`signal_status'
/Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb.rb:492:in `block (2 levels) in eval_input'
/Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/context.rb:380:in`evaluate'
/Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/workspace.rb:86:in `evaluate'
/Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/workspace.rb:86:in`eval'
(irb):4:in `irb_binding'
(irb):4:in`set_rgb'

-- C level backtrace information -------------------------------------------

-- Other runtime information -----------------------------------------------
- Loaded script: irb
- Loaded features:
  
  0 enumerator.so
  1 enc/encdb.so
  2 enc/trans/transdb.so
  3 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/x86_64-darwin13.4.0/rbconfig.rb
  4 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/thread.rb
  5 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/compatibility.rb
  6 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/defaults.rb
  7 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/deprecate.rb
  8 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/errors.rb
  9 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/version.rb
  10 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/requirement.rb
  11 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/platform.rb
  12 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/basic_specification.rb
  13 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/stub_specification.rb
  14 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/util/stringio.rb
  15 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb
  16 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/exceptions.rb
  17 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_gem.rb
  18 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/monitor.rb
  19 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb
  20 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems.rb
  21 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/e2mmap.rb
  22 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/init.rb
  23 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/workspace.rb
  24 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/inspector.rb
  25 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/context.rb
  26 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/extend-command.rb
  27 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/output-method.rb
  28 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/notifier.rb
  29 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/slex.rb
  30 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/ruby-token.rb
  31 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/ruby-lex.rb
  32 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/src_encoding.rb
  33 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/magic-file.rb
  34 readline.so
  35 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/input-method.rb
  36 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/locale.rb
  37 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb.rb
  38 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/path_support.rb
  39 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/dependency.rb
  40 /Users/davidddouglas/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/irb/completion.rb
  41 /Users/davidddouglas/.rvm/scripts/irbrc.rb
  42 /Users/davidddouglas/.rvm/gems/ruby-2.0.0-p598/gems/rb-blink1-0.0.7/ext/blink1/blink1.bundle
  43 /Users/davidddouglas/.rvm/gems/ruby-2.0.0-p598/gems/rb-blink1-0.0.7/lib/blink1/version.rb
  44 /Users/davidddouglas/.rvm/gems/ruby-2.0.0-p598/gems/rb-blink1-0.0.7/lib/blink1.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
Don't forget to include the above Crash Report log file.
For details: http://www.ruby-lang.org/bugreport.html

Abort trap: 6

**Comment by joshproehl** [comment]
I am also experiencing segfaults on OSX 10.10. It occurs when trying to set colors, set via fades, calling the .on method...

It was working, now it's segfaulting, and I haven't been able break it out of the segfaults.
